# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8_Cc6EMneljId24LW0ATKR98pURGGxw
"""

#Programe for find Factorial Number
num=int(input("Enter a Number :"))
fact=1
while num>0:
  fact=fact*num
  num=num-1
print("Factorial Number is:",fact)