# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8_Cc6EMneljId24LW0ATKR98pURGGxw
"""

#Programe to check number is pallindrome or not
i=int(input("Enter a Number :"))
x=i
rev=0
while i>0:
  rev=rev*10+i%10
  i=i//10
if x==rev:
  print("Number is Pallindrome")
else:
  print("Not a Pallindrome ")