# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8_Cc6EMneljId24LW0ATKR98pURGGxw
"""

#Program to Reverse a Number
i=int(input("Enter a Number :"))
rev=0
while i>0:
  rev=rev*10+i%10
  i=i//10
print("reverse number is :",rev)